package com.kedu.arias.product.dto;
/*
RESERVATION_SEQ	NOT NULL	NUMBER
PRODUCT_SEQ		NUMBER
MEMBER_ID		VARCHAR2(30)
RESERV_COUNT	NOT NULL	NUMBER
CHECKIN_DT	NOT NULL	DATE
CHECKOUT_DT	NOT NULL	DATE
REG_DT		DATE
MEMBER_INTRO		VARCHAR2(1000)
RESERV_STATUS		NUMBER
*/
public class ReservationDto {
	Integer reservation_seq;
}
